---
#: GitHub actions workflow for building chroot tarballs
#: for ma'shmallow-0 testing environments.

name: mash-ci

on:
  # Suppressing builds on push for now; leaving only chron-based builds.

  push:
    branches:
      # any branches (must quote the asterisk)
      - '*'
      # $default-branch (must be main) doesn't seem to work
      - main

jobs:
  test-mash:

    runs-on: ubuntu-latest
    environment: STAGE

    env:
      # TODO: consider getting the mash-0-chroot-setup release version from somewhere else
      CHROOT_TARBALLS_URL: https://github.com/ya55en/mash-0-chroot-setup/releases/download/v0.0.5
      CHROOT: /tmp/mash-ramdisk
      CODENAME: focal

    steps:
      - uses: actions/checkout@v2
      - run: git submodule sync --recursive
      - run: git submodule update --init --force --recursive --depth=1
      - run: sudo apt-get update
      # - run: sudo apt-get upgrade
      - run: sudo apt-get install -y make curl
      - run: sudo apt-get clean

      - run: sudo mkdir "$CHROOT"
      - run: cd chroot-setup && ./scripts/create-dot-env.sh <.env.mk.sample >.env.mk
      - run: cd chroot-setup && make clean-build  # creates ./chroot-setup/build/

      - run: curl -sSL "$CHROOT_TARBALLS_URL/${CODENAME}-headless.tar.gz" -o ./chroot-setup/build/${CODENAME}-headless.tar.gz
      - run: curl -sSL "$CHROOT_TARBALLS_URL/${CODENAME}-mate-desktop.tar.gz" -o ./chroot-setup/build/${CODENAME}-mate-desktop.tar.gz

      - run: cd chroot-setup && make mate-desktop-up
      # - run: make test-mash-core
      - run: make test-quick
      - run: make test-standard
      - run: cd chroot-setup && make mate-desktop-down
